// Tray icon and menu (Open AudioDeck, Pause automation, Quit).

import { Menu, Tray, nativeImage } from "electron";
import { TRAY_ICON_16, TRAY_ICON_32 } from "./trayIcon.js";

export interface TrayActions {
  openWindow: () => void;
  setPaused: (paused: boolean) => void | Promise<void>;
  quit: () => void;
}

export interface TrayHandle {
  tray: Tray;
  /** Keep the menu checkbox in sync when pause is toggled from the UI. */
  setPausedChecked: (paused: boolean) => void;
}

/**
 * The brand mark, generated by design/make-icon.mjs from the same geometry the
 * app draws in `.brand-mark`. Both sizes are added so Windows picks by DPI
 * rather than scaling 16 up and softening it; the 16 is the upright cut, since
 * the tilted frame turns to mush at that size.
 */
function trayImage() {
  const image = nativeImage.createFromDataURL(`data:image/png;base64,${TRAY_ICON_16}`);
  image.addRepresentation({
    scaleFactor: 2,
    dataURL: `data:image/png;base64,${TRAY_ICON_32}`,
  });
  return image;
}

export function createTray(actions: TrayActions): TrayHandle {
  const tray = new Tray(trayImage());
  tray.setToolTip("AudioDeck");

  const menu = Menu.buildFromTemplate([
    {
      label: "Open AudioDeck",
      click: () => actions.openWindow(),
    },
    {
      id: "pause",
      label: "Pause automation",
      type: "checkbox",
      checked: false,
      click: (item) => void actions.setPaused(item.checked),
    },
    { type: "separator" },
    {
      label: "Quit",
      click: () => actions.quit(),
    },
  ]);
  tray.setContextMenu(menu);
  tray.on("click", () => actions.openWindow());

  const pauseItem = menu.getMenuItemById("pause");
  return {
    tray,
    setPausedChecked: (paused) => {
      if (pauseItem !== null) pauseItem.checked = paused;
    },
  };
}
