import { describe, expect, it } from "vitest";
import { applyProfiles, removeProfiles } from "./apply.js";
import { flatProfile } from "./render.js";
import { detectEqApo, parseRegValue } from "./detect.js";
import type { FileIo } from "./apply.js";
import type { DeviceSection } from "./render.js";

/** An in-memory filesystem, so these tests never touch a real install. */
function fakeIo(initial: Record<string, string> = {}) {
  const files = new Map(Object.entries(initial));
  const io: FileIo = {
    read: async (file) => files.get(file) ?? null,
    write: async (file, text) => void files.set(file, text),
    remove: async (file) => void files.delete(file),
  };
  return { io, files };
}

const CONFIG_DIR = "C:\\Program Files\\EqualizerAPO\\config";
const MAIN = `${CONFIG_DIR}\\config.txt`;
const OURS = `${CONFIG_DIR}\\audiodeck.txt`;
const STOCK = "Preamp: -6 dB\nInclude: example.txt\n";

const section = (match: string): DeviceSection => ({
  match,
  profile: { ...flatProfile(), bassBoost: 4 },
});

describe("applyProfiles", () => {
  it("writes our config and links it from theirs", async () => {
    const { io, files } = fakeIo({ [MAIN]: STOCK });
    const result = await applyProfiles(io, CONFIG_DIR, [section("{guid-a}")]);

    expect(result.configFile).toBe(OURS);
    expect(result.linkedInclude).toBe(true);
    expect(files.get(OURS)).toContain("Device: {guid-a}");
    expect(files.get(MAIN)).toContain("Include: audiodeck.txt");
  });

  it("leaves the user's own config otherwise untouched", async () => {
    const { io, files } = fakeIo({ [MAIN]: STOCK });
    await applyProfiles(io, CONFIG_DIR, [section("{guid-a}")]);
    expect(files.get(MAIN)).toContain("Preamp: -6 dB");
    expect(files.get(MAIN)).toContain("Include: example.txt");
  });

  it("does not rewrite their config on a second apply", async () => {
    // Profiles change often. Their file should be written once, ever.
    const { io, files } = fakeIo({ [MAIN]: STOCK });
    await applyProfiles(io, CONFIG_DIR, [section("{guid-a}")]);
    const afterFirst = files.get(MAIN);

    const second = await applyProfiles(io, CONFIG_DIR, [section("{guid-b}")]);
    expect(second.linkedInclude).toBe(false);
    expect(files.get(MAIN)).toBe(afterFirst);
    // Ours is still updated, though.
    expect(files.get(OURS)).toContain("Device: {guid-b}");
  });

  it("copes with no config.txt at all", async () => {
    // A user can delete it; Equalizer APO recreates it, but we should not
    // crash in the window where it is missing.
    const { io, files } = fakeIo();
    await applyProfiles(io, CONFIG_DIR, [section("{guid-a}")]);
    expect(files.get(MAIN)).toBe("Include: audiodeck.txt\n");
  });

  it("writes an empty profile set without error", async () => {
    const { io, files } = fakeIo({ [MAIN]: STOCK });
    await applyProfiles(io, CONFIG_DIR, []);
    expect(files.get(OURS)).toContain("Generated by AudioDeck");
  });
});

describe("removeProfiles", () => {
  it("leaves the machine as it was found", async () => {
    const { io, files } = fakeIo({ [MAIN]: STOCK });
    await applyProfiles(io, CONFIG_DIR, [section("{guid-a}")]);
    await removeProfiles(io, CONFIG_DIR);

    expect(files.get(MAIN)).toBe(STOCK);
    expect(files.has(OURS)).toBe(false);
  });

  it("is safe to run when nothing was ever applied", async () => {
    const { io, files } = fakeIo({ [MAIN]: STOCK });
    await expect(removeProfiles(io, CONFIG_DIR)).resolves.toBeUndefined();
    expect(files.get(MAIN)).toBe(STOCK);
  });

  it("is safe to run twice", async () => {
    const { io } = fakeIo({ [MAIN]: STOCK });
    await applyProfiles(io, CONFIG_DIR, [section("{guid-a}")]);
    await removeProfiles(io, CONFIG_DIR);
    await expect(removeProfiles(io, CONFIG_DIR)).resolves.toBeUndefined();
  });

  it("still removes our file when their config has vanished", async () => {
    const { io, files } = fakeIo();
    await applyProfiles(io, CONFIG_DIR, [section("{guid-a}")]);
    files.delete(MAIN);
    await removeProfiles(io, CONFIG_DIR);
    expect(files.has(OURS)).toBe(false);
  });
});

describe("parseRegValue", () => {
  // Real `reg query` output, captured 2026-08-01.
  const OUTPUT = [
    "",
    "HKEY_LOCAL_MACHINE\\SOFTWARE\\EqualizerAPO",
    "    InstallPath    REG_SZ    C:\\Program Files\\EqualizerAPO",
    "    ConfigPath    REG_SZ    C:\\Program Files\\EqualizerAPO\\config",
    "    EnableTrace    REG_SZ    false",
    "",
  ].join("\r\n");

  it("reads a value whose data contains spaces", () => {
    expect(parseRegValue(OUTPUT, "ConfigPath")).toBe("C:\\Program Files\\EqualizerAPO\\config");
  });

  it("returns null for a value that is not there", () => {
    expect(parseRegValue(OUTPUT, "Nonexistent")).toBeNull();
  });

  it("does not confuse one value name for another's prefix", () => {
    expect(parseRegValue(OUTPUT, "Install")).toBeNull();
  });
});

describe("detectEqApo", () => {
  const OUTPUT =
    "    InstallPath    REG_SZ    C:\\EQ\r\n    ConfigPath    REG_SZ    C:\\EQ\\config\r\n";

  it("reports the install when the registry has it", async () => {
    const found = await detectEqApo({ queryRegistry: async () => OUTPUT });
    expect(found).toEqual({ installPath: "C:\\EQ", configPath: "C:\\EQ\\config" });
  });

  it("reports absent when the key is missing", async () => {
    expect(await detectEqApo({ queryRegistry: async () => null })).toBeNull();
  });

  it("reports absent rather than guessing when the key is half written", async () => {
    const partial = "    InstallPath    REG_SZ    C:\\EQ\r\n";
    expect(await detectEqApo({ queryRegistry: async () => partial })).toBeNull();
  });
});
