// Where the generated reverb impulse responses live on disk.
//
// Generated by scripts/make-reverb-ir.mjs rather than committed, and bundled
// as extraResources so a packaged build can copy them next to Equalizer APO's
// config, which is where Convolution resolves its paths from.

import { app } from "electron";
import path from "node:path";
import { irFileName } from "./render.js";
import type { ImpulseResponses } from "./apply.js";

export const impulseResponses: ImpulseResponses = {
  sourcePath: (rate: number): string =>
    app.isPackaged
      ? path.join(process.resourcesPath, "ir", irFileName(rate))
      : path.join(app.getAppPath(), "assets", "ir", irFileName(rate)),
};
