// Turns device EQ profiles into an Equalizer APO configuration file.
//
// PURE: no I/O, no Electron, no filesystem. Everything that decides what the
// audio sounds like is here, so it can be tested by reading the text it emits
// rather than by listening.
//
// No automatic preamp. An earlier version emitted `Preamp: -<peak boost>` to
// guarantee nothing could clip, which made every boost inaudible: raising the
// bass 8 dB and pulling everything down 8 dB leaves the bass where it started
// and merely makes the rest quieter. Reported from real listening as "the only
// thing I can hear is the audio getting lower". A boost has to boost, so what
// the user dials is what is written, and loud material with a large boost may
// clip exactly as it would in any other equalizer.
//
// The `Device:` matching string is supplied by the caller rather than derived
// here: Equalizer APO matches on the name its own Configurator shows, which is
// not AudioDeck's endpoint id, and the mapping is established against a real
// installation instead of guessed.

/** Centre frequencies of the ten bands, matching the curve drawn in the UI. */
export const BANDS = [32, 64, 125, 250, 500, 1000, 2000, 4000, 8000, 16000] as const;

/** Gain limits, per band and per effect. Beyond this it stops being useful. */
export const MAX_BAND_DB = 12;
export const MAX_EFFECT_DB = 12;
/**
 * Bass gets more range than the other effects. A low shelf is doing its work
 * over a narrow slice of the spectrum where there is usually headroom to
 * spare, and 12 dB was not enough to be worth the slider. The same range on
 * the presence shelf would just be harsh.
 */
export const MAX_BASS_DB = 20;

/** Corner frequencies for the two shelf effects. */
const BASS_FC_HZ = 100;
const CLARITY_FC_HZ = 6000;

export interface EqProfile {
  enabled: boolean;
  /** Gain in dB per band, indexed against BANDS. */
  bands: number[];
  /** Low shelf, dB. */
  bassBoost: number;
  /** High shelf, dB. */
  clarity: number;
  /** Stereo width as a percentage; 100 leaves the signal untouched. */
  width: number;
}

export interface DeviceSection {
  /** The string Equalizer APO matches this device on. */
  match: string;
  profile: EqProfile;
}

export function flatProfile(): EqProfile {
  return {
    enabled: true,
    bands: BANDS.map(() => 0),
    bassBoost: 0,
    clarity: 0,
    width: 100,
  };
}

const HEADER = [
  "# Generated by AudioDeck. Every line below is rewritten whenever a profile",
  "# changes, so edits here do not survive. Change them in AudioDeck's Studio",
  "# tab instead, or use Settings > Remove audio effects to take them out.",
].join("\n");

/**
 * Does this rendered config actually ask Equalizer APO to do anything?
 *
 * A profile can exist and still render to nothing: every band at zero, every
 * effect at rest. Deciding on the presence of profiles rather than on the
 * presence of directives is how AudioDeck ended up writing a comments-only
 * file and linking it from someone's config for no reason.
 */
export function hasDirectives(config: string): boolean {
  return config
    .split(/\r?\n/)
    .some((line) => line.trim() !== "" && !line.trimStart().startsWith("#"));
}

export function renderConfig(sections: readonly DeviceSection[]): string {
  const blocks = sections
    .filter((s) => s.profile.enabled)
    .map((s) => renderSection(s))
    .filter((text) => text !== null);

  return blocks.length === 0 ? `${HEADER}\n` : `${HEADER}\n\n${blocks.join("\n\n")}\n`;
}

function renderSection({ match, profile }: DeviceSection): string | null {
  const lines: string[] = [];
  const bands = normaliseBands(profile.bands);
  const bass = clamp(profile.bassBoost, -MAX_BASS_DB, MAX_BASS_DB);
  const clarity = clamp(profile.clarity, -MAX_EFFECT_DB, MAX_EFFECT_DB);
  const width = clamp(profile.width, 0, 200);

  if (bands.some((g) => g !== 0)) {
    lines.push(`GraphicEQ: ${bands.map((g, i) => `${BANDS[i]} ${fmt(g)}`).join("; ")}`);
  }
  if (bass !== 0) {
    lines.push(`Filter: ON LS Fc ${BASS_FC_HZ} Hz Gain ${fmt(bass)} dB`);
  }
  if (clarity !== 0) {
    lines.push(`Filter: ON HS Fc ${CLARITY_FC_HZ} Hz Gain ${fmt(clarity)} dB`);
  }
  lines.push(...renderWidth(width));

  // A device whose profile does nothing gets no section at all, rather than a
  // Device: line with nothing under it.
  if (lines.length === 0) return null;
  return [`Device: ${match}`, ...lines].join("\n");
}

/**
 * Narrowing towards mono, expressed as a channel matrix.
 *
 *   M = (L+R)/2,  L' = aL + bR,  R' = bL + aR,  a = (1+w)/2, b = (1-w)/2
 *
 * At w = 1 that is the identity, so nothing is emitted. At w = 0 both
 * coefficients are 0.5, which is mono.
 *
 * Above 100 % this widens, which needs b < 0: each channel subtracts some of
 * the other. Earlier attempts at that destroyed the audio, but every one of
 * them emitted the term as `-0.35*ADR`, leaving `ADL-0.35` for Equalizer APO
 * to make sense of. Its grammar joins terms with `+`, so the term is now
 * written `+-0.35*ADR`. Whether that is the whole story is still unproven.
 *
 * The originals are snapshotted into virtual channels first, because Equalizer
 * APO applies the assignments in a Copy line SEQUENTIALLY: writing the matrix
 * directly computes R from the already-modified L.
 */
function renderWidth(widthPercent: number): string[] {
  const w = widthPercent / 100;
  if (w === 1) return [];
  const a = (1 + w) / 2;
  const b = (1 - w) / 2;
  return [
    "Copy: ADL=L ADR=R",
    `Copy: L=${factor(a)}*ADL${signed(b)}*ADR R=${factor(a)}*ADR${signed(b)}*ADL`,
  ];
}

function normaliseBands(bands: readonly number[]): number[] {
  return BANDS.map((_, i) => clamp(bands[i] ?? 0, -MAX_BAND_DB, MAX_BAND_DB));
}

function clamp(value: number, min: number, max: number): number {
  if (!Number.isFinite(value)) return 0;
  return Math.min(max, Math.max(min, value));
}

/** One decimal place, and never "-0.0". */
function fmt(value: number): string {
  const rounded = round(value);
  return (rounded === 0 ? 0 : rounded).toFixed(1);
}

function factor(value: number): string {
  const rounded = Math.round(value * 1000) / 1000;
  return (rounded === 0 ? 0 : rounded).toString();
}

/**
 * A matrix term, always introduced by a `+`, so a negative coefficient reads
 * as `+-0.35*ADR` rather than `-0.35*ADR`.
 *
 * Equalizer APO's grammar joins terms with `+`; every example it ships does.
 * Writing `1.35*ADL-0.35*ADR` instead leaves `ADL-0.35` for it to interpret,
 * which is very likely what mangled the audio at every width above 100 %.
 */
function signed(value: number): string {
  const rounded = Math.round(value * 1000) / 1000;
  return `+${factor(rounded)}`;
}

function round(value: number): number {
  return Math.round(value * 10) / 10;
}
