// Turns device EQ profiles into an Equalizer APO configuration file.
//
// PURE: no I/O, no Electron, no filesystem. Everything that decides what the
// audio sounds like is here, so it can be tested by reading the text it emits
// rather than by listening.
//
// The `Device:` matching string is supplied by the caller rather than derived
// here: Equalizer APO matches on the name its own Configurator shows, which is
// not AudioDeck's endpoint id, and the mapping is established against a real
// installation instead of guessed.

/** Centre frequencies of the ten bands, matching the curve drawn in the UI. */
export const BANDS = [32, 64, 125, 250, 500, 1000, 2000, 4000, 8000, 16000] as const;

/** Gain limits, per band and per effect. Beyond this it stops being useful. */
export const MAX_BAND_DB = 12;
export const MAX_EFFECT_DB = 12;

/** Corner frequencies for the two shelf effects. */
const BASS_FC_HZ = 100;
const CLARITY_FC_HZ = 6000;

export interface EqProfile {
  enabled: boolean;
  /** Gain in dB per band, indexed against BANDS. */
  bands: number[];
  /** Low shelf, dB. */
  bassBoost: number;
  /** High shelf, dB. */
  clarity: number;
  /** Stereo width as a percentage; 100 leaves the signal untouched. */
  width: number;
}

export interface DeviceSection {
  /** The string Equalizer APO matches this device on. */
  match: string;
  profile: EqProfile;
}

export function flatProfile(): EqProfile {
  return {
    enabled: true,
    bands: BANDS.map(() => 0),
    bassBoost: 0,
    clarity: 0,
    width: 100,
  };
}

const HEADER = [
  "# Generated by AudioDeck. Every line below is rewritten whenever a profile",
  "# changes, so edits here do not survive. Change them in AudioDeck's Studio",
  "# tab instead, or use Settings > Remove audio effects to take them out.",
].join("\n");

export function renderConfig(sections: readonly DeviceSection[]): string {
  const blocks = sections
    .filter((s) => s.profile.enabled)
    .map((s) => renderSection(s))
    .filter((text) => text !== null);

  return blocks.length === 0 ? `${HEADER}\n` : `${HEADER}\n\n${blocks.join("\n\n")}\n`;
}

function renderSection({ match, profile }: DeviceSection): string | null {
  const lines: string[] = [];
  const bands = normaliseBands(profile.bands);
  const bass = clamp(profile.bassBoost, -MAX_EFFECT_DB, MAX_EFFECT_DB);
  const clarity = clamp(profile.clarity, -MAX_EFFECT_DB, MAX_EFFECT_DB);
  const width = clamp(profile.width, 0, 200);

  const headroom = requiredHeadroomDb(bands, bass, clarity, width);
  if (headroom > 0) lines.push(`Preamp: ${fmt(-headroom)} dB`);

  if (bands.some((g) => g !== 0)) {
    lines.push(`GraphicEQ: ${bands.map((g, i) => `${BANDS[i]} ${fmt(g)}`).join("; ")}`);
  }
  if (bass !== 0) {
    lines.push(`Filter: ON LS Fc ${BASS_FC_HZ} Hz Gain ${fmt(bass)} dB`);
  }
  if (clarity !== 0) {
    lines.push(`Filter: ON HS Fc ${CLARITY_FC_HZ} Hz Gain ${fmt(clarity)} dB`);
  }
  const copy = renderWidth(width);
  if (copy !== null) lines.push(copy);

  // A device whose profile does nothing gets no section at all, rather than a
  // Device: line with nothing under it.
  if (lines.length === 0) return null;
  return [`Device: ${match}`, ...lines].join("\n");
}

/**
 * Mid-side widening expressed as a channel matrix.
 *
 *   M = (L+R)/2,  S = (L-R)/2,  L' = M + wS,  R' = M - wS
 *
 * which expands to L' = aL + bR and R' = bL + aR with a = (1+w)/2 and
 * b = (1-w)/2. At w = 1 that is a = 1, b = 0: the identity, so it is omitted
 * entirely rather than written as a no-op matrix. At w = 0 both are 0.5, which
 * is mono.
 */
function renderWidth(widthPercent: number): string | null {
  const w = widthPercent / 100;
  if (w === 1) return null;
  const a = (1 + w) / 2;
  const b = (1 - w) / 2;
  return `Copy: L=${factor(a)}*L${signed(b)}*R R=${factor(a)}*R${signed(b)}*L`;
}

/**
 * How much to pull the signal down so nothing added above can clip.
 *
 * Pessimistic on purpose: it assumes the worst case where the loudest band,
 * both shelves and the widening matrix all line up on the same sample. Being
 * quieter than strictly necessary is a fair trade against a distorted peak,
 * and the user can make it back up with the system volume.
 */
function requiredHeadroomDb(
  bands: readonly number[],
  bass: number,
  clarity: number,
  widthPercent: number,
): number {
  const peakBand = Math.max(0, ...bands);
  const w = widthPercent / 100;
  const a = (1 + w) / 2;
  const b = (1 - w) / 2;
  // Worst-case channel gain from the matrix, in dB, when it can exceed unity.
  const matrixGain = Math.abs(a) + Math.abs(b);
  const matrixDb = matrixGain > 1 ? 20 * Math.log10(matrixGain) : 0;
  const total = peakBand + Math.max(0, bass) + Math.max(0, clarity) + matrixDb;
  return round(Math.max(0, total));
}

function normaliseBands(bands: readonly number[]): number[] {
  return BANDS.map((_, i) => clamp(bands[i] ?? 0, -MAX_BAND_DB, MAX_BAND_DB));
}

function clamp(value: number, min: number, max: number): number {
  if (!Number.isFinite(value)) return 0;
  return Math.min(max, Math.max(min, value));
}

/** One decimal place, and never "-0.0". */
function fmt(value: number): string {
  const rounded = round(value);
  return (rounded === 0 ? 0 : rounded).toFixed(1);
}

function factor(value: number): string {
  const rounded = Math.round(value * 1000) / 1000;
  return (rounded === 0 ? 0 : rounded).toString();
}

/** A matrix term with its sign attached, so terms can be concatenated. */
function signed(value: number): string {
  const rounded = Math.round(value * 1000) / 1000;
  return rounded < 0 ? `-${factor(-rounded)}` : `+${factor(rounded)}`;
}

function round(value: number): number {
  return Math.round(value * 10) / 10;
}
