import { describe, expect, it } from "vitest";
import { BANDS, flatProfile, renderConfig } from "./render.js";
import type { DeviceSection, EqProfile } from "./render.js";

function profile(overrides: Partial<EqProfile> = {}): EqProfile {
  return { ...flatProfile(), ...overrides };
}

function section(overrides: Partial<EqProfile> = {}, match = "Speakers"): DeviceSection {
  return { match, profile: profile(overrides) };
}

/** The emitted lines, without the header comment or blank lines. */
function lines(text: string): string[] {
  return text
    .split("\n")
    .filter((l) => l.trim() !== "" && !l.startsWith("#"));
}

/** The Preamp line, or null. Found rather than indexed, so adding a line
 *  elsewhere in the section does not break every headroom test. */
function preamp(text: string): string | null {
  return lines(text).find((l) => l.startsWith("Preamp:")) ?? null;
}

describe("renderConfig", () => {
  it("says who wrote the file and that edits do not survive", () => {
    // Anyone who opens config.txt should learn where the settings really live.
    expect(renderConfig([])).toContain("Generated by AudioDeck");
    expect(renderConfig([])).toContain("Studio");
  });

  it("emits nothing for a flat profile", () => {
    // A device set to do nothing must not sit in the audio path doing nothing
    // expensively, nor claim a Device: section with no filters under it.
    expect(lines(renderConfig([section()]))).toEqual([]);
  });

  it("emits nothing at all when there are no devices", () => {
    expect(lines(renderConfig([]))).toEqual([]);
  });

  it("skips a disabled profile entirely", () => {
    // The per-device bypass has to remove the processing, not zero it: this is
    // what makes an A/B against unprocessed audio honest.
    const on = section({ bands: [6, 0, 0, 0, 0, 0, 0, 0, 0, 0] }, "Headset");
    const off: DeviceSection = { ...on, profile: { ...on.profile, enabled: false } };
    expect(lines(renderConfig([off]))).toEqual([]);
    expect(lines(renderConfig([on])).length).toBeGreaterThan(0);
  });

  it("writes the curve as one GraphicEQ line over the band frequencies", () => {
    const bands = [3, 0, -2, 0, 0, 0, 0, 0, 0, 1.5];
    const out = lines(renderConfig([section({ bands })]));
    const eq = out.find((l) => l.startsWith("GraphicEQ:"));
    expect(eq).toBe(
      "GraphicEQ: 32 3.0; 64 0.0; 125 -2.0; 250 0.0; 500 0.0; 1000 0.0; " +
        "2000 0.0; 4000 0.0; 8000 0.0; 16000 1.5",
    );
    expect(BANDS).toHaveLength(bands.length);
  });

  it("writes bass boost as a low shelf and clarity as a high shelf", () => {
    const out = lines(renderConfig([section({ bassBoost: 4, clarity: 2.5 })]));
    expect(out).toContain("Filter: ON LS Fc 100 Hz Gain 4.0 dB");
    expect(out).toContain("Filter: ON HS Fc 6000 Hz Gain 2.5 dB");
  });

  it("omits an effect that is set to zero", () => {
    const out = lines(renderConfig([section({ bassBoost: 3 })]));
    expect(out.some((l) => l.includes("LS"))).toBe(true);
    expect(out.some((l) => l.includes("HS"))).toBe(false);
  });

  describe("stereo width", () => {
    it("emits nothing at 100 percent", () => {
      // The identity matrix is not worth the cycles or the file noise.
      expect(lines(renderConfig([section({ width: 100 })]))).toEqual([]);
    });

    it("collapses to mono at 0 percent", () => {
      const out = lines(renderConfig([section({ width: 0 })]));
      expect(out).toContain("Copy: L=0.5*L+0.5*R R=0.5*R+0.5*L");
    });

    it("subtracts the opposite channel when widening", () => {
      // w = 1.5 gives a = 1.25, b = -0.25.
      const out = lines(renderConfig([section({ width: 150 })]));
      expect(out).toContain("Copy: L=1.25*L-0.25*R R=1.25*R-0.25*L");
    });
  });

  describe("preamp", () => {
    it("is absent when nothing is boosted", () => {
      expect(preamp(renderConfig([section({ bands: [-6, 0, 0, 0, 0, 0, 0, 0, 0, 0] })]))).toBeNull();
    });

    it("offsets the loudest boost so a peak cannot clip", () => {
      expect(preamp(renderConfig([section({ bands: [3, 8, 0, 0, 0, 0, 0, 0, 0, 0] })]))).toBe(
        "Preamp: -8.0 dB",
      );
    });

    it("counts the shelves as well as the curve", () => {
      const text = renderConfig([
        section({ bands: [4, 0, 0, 0, 0, 0, 0, 0, 0, 0], bassBoost: 3, clarity: 2 }),
      ]);
      expect(preamp(text)).toBe("Preamp: -9.0 dB");
    });

    it("counts the widening matrix, which can also exceed unity", () => {
      // At 200 percent a = 1.5 and b = -0.5, so a fully anti-correlated pair
      // (L = +1, R = -1) comes out at |a| + |b| = 2.0, which is 6 dB.
      expect(preamp(renderConfig([section({ width: 200 })]))).toBe("Preamp: -6.0 dB");
    });

    it("comes before the filters it compensates for", () => {
      const out = lines(renderConfig([section({ bands: [6, 0, 0, 0, 0, 0, 0, 0, 0, 0] })]));
      expect(out[0]).toBe("Device: Speakers");
      expect(out[1]).toBe("Preamp: -6.0 dB");
    });

    it("ignores cuts, which cannot clip", () => {
      const text = renderConfig([
        section({ bands: [-12, 0, 0, 0, 0, 0, 0, 0, 0, 0], bassBoost: -6 }),
      ]);
      expect(preamp(text)).toBeNull();
    });
  });

  describe("robustness", () => {
    it("clamps gains beyond the supported range", () => {
      const out = lines(renderConfig([section({ bands: [99, 0, 0, 0, 0, 0, 0, 0, 0, 0], bassBoost: 99 })]));
      expect(out.join("\n")).toContain("32 12.0");
      expect(out.join("\n")).toContain("Gain 12.0 dB");
    });

    it("survives a short or ragged band array", () => {
      // Config written by an older version, or hand-edited.
      const out = lines(renderConfig([{ match: "X", profile: { ...flatProfile(), bands: [5] } }]));
      expect(out.join("\n")).toContain("32 5.0");
      expect(out.join("\n")).toContain("64 0.0");
    });

    it("treats NaN as no change rather than emitting it", () => {
      const bands = [Number.NaN, 0, 0, 0, 0, 0, 0, 0, 0, 0];
      const out = renderConfig([section({ bands, bassBoost: Number.POSITIVE_INFINITY })]);
      expect(out).not.toContain("NaN");
      expect(out).not.toContain("Infinity");
    });

    it("never writes negative zero", () => {
      expect(renderConfig([section({ bands: [-0.04, 0, 0, 0, 0, 0, 0, 0, 0, 0] })])).not.toContain(
        "-0.0",
      );
    });
  });

  it("gives each device its own section, in order", () => {
    const out = lines(
      renderConfig([
        section({ bassBoost: 3 }, "Speakers"),
        section({ clarity: 2 }, "LG TV"),
      ]),
    );
    expect(out[0]).toBe("Device: Speakers");
    expect(out).toContain("Device: LG TV");
    expect(out.indexOf("Device: Speakers")).toBeLessThan(out.indexOf("Device: LG TV"));
  });
});
