// Fetch Anton and Archivo as local woff2 plus a fonts.css with the original
// @font-face blocks (unicode-range intact), so the app never calls the network
// at runtime. Re-run to refresh; output is committed.

import { mkdirSync, writeFileSync } from "node:fs";
import path from "node:path";
import { fileURLToPath } from "node:url";

const root = path.resolve(path.dirname(fileURLToPath(import.meta.url)), "..");
const outDir = path.join(root, "src", "renderer", "src", "assets", "fonts");
mkdirSync(outDir, { recursive: true });

const CHROME_UA =
  "Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/126.0.0.0 Safari/537.36";
const API =
  "https://fonts.googleapis.com/css2?family=Anton&family=Archivo:wght@400;600;700;800;900&display=swap";

const css = await (await fetch(API, { headers: { "User-Agent": CHROME_UA } })).text();

let index = 0;
const seen = new Map();
let localCss = "/* Generated by scripts/fetch-fonts.mjs. Do not edit by hand. */\n";

for (const block of css.split("@font-face").slice(1)) {
  const url = /url\((https:[^)]+\.woff2)\)/.exec(block)?.[1];
  if (url === undefined) continue;
  let file = seen.get(url);
  if (file === undefined) {
    const family = /font-family:\s*'([^']+)'/.exec(block)?.[1] ?? "font";
    index += 1;
    file = `${family.toLowerCase().replace(/\s+/g, "-")}-${index}.woff2`;
    const bytes = Buffer.from(await (await fetch(url)).arrayBuffer());
    writeFileSync(path.join(outDir, file), bytes);
    seen.set(url, file);
  }
  localCss += `@font-face${block.replace(/url\(https:[^)]+\.woff2\)/, `url('./fonts/${file}')`)}`;
}

writeFileSync(path.join(outDir, "..", "fonts.css"), localCss, "utf8");
console.log(`wrote ${seen.size} woff2 files and fonts.css`);
